language: node_js

os:
  - linux

node_js:
  - "10"
  - "12"

install:
  - npm install
  - npm install -g codecov

stages:
  - test
  - name: releaseNpm
    if: branch = master

jobs:
  include:
    - stage: test
      name: "Run test scripts"
      node_js: "14"
      script:
        - npm run test
        - codecov

    - stage: releaseNpm
      name: "Release npm package"
      node_js: "14"
      script:
        - echo "Release npm package..."
        - npm run build
        - npm run dts
      deploy:
        provider: npm
        email: 1558267774@qq.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master

notifications:
  email: false
